### ISSUE TITLE
Release of datasets

### ISSUE THREAD

**Issue by miquel-espinosa** [hzxie/city-dreamer#3]
Hi. Will the datasets be released? Where/when?
Thanks

**Comment by hzxie** [comment]
The dataset will be publicly available once the paper is accepted.

**Comment by hzxie** [comment]
The OSM and GoogleEarth datasets have been released.

- [OSM Dataset](https://gateway.infinitescript.com/s/OSM)
- [GoogleEarth Dataset](https://gateway.infinitescript.com/s/GoogleEarth)

**Comment by hzxie** [comment]
<img width="1564" alt="Screenshot 2024-05-09 at 7 56 36 AM" src="https://github.com/hzxie/CityDreamer/assets/1730504/743b1b16-160c-4c92-8d03-ca9fda455776">

1. Input the email address into the textbox.
2. Complete the reCAPTCHA test.
