### ISSUE TITLE
how to find height fields in OSM dataset? 

### ISSUE THREAD

**Issue by RWLinno** [hzxie/city-dreamer#4]
Thank you for your work! Regarding the section 4.1. of the paper The OSM Dataset, I was wondering if the height fields are originally present in the OpenStreetMap dataset? But I didn't find it, and I additionally used tools like osmnx and arcmap.

**Comment by hzxie** [comment]
Yes. For each building, there will be a field named "height".
Please refer to https://wiki.openstreetmap.org/wiki/Key:height
